//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceWars.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpaceWars.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Connected.
        /// </summary>
        internal static string GameServer_Log_ClientConnected {
            get {
                return ResourceManager.GetString("GameServer_Log_ClientConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Failed to Connect.
        /// </summary>
        internal static string GameServer_Log_ClientConnectFailed {
            get {
                return ResourceManager.GetString("GameServer_Log_ClientConnectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Disconnected.
        /// </summary>
        internal static string GameServer_Log_ClientDisconnected {
            get {
                return ResourceManager.GetString("GameServer_Log_ClientDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties file could not be loaded; possibly corrupt..
        /// </summary>
        internal static string GameServer_Log_PropertiesLoadFailed {
            get {
                return ResourceManager.GetString("GameServer_Log_PropertiesLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listening for Game Clients on Port 11000.
        /// </summary>
        internal static string GameServer_Log_ServerConnected {
            get {
                return ResourceManager.GetString("GameServer_Log_ServerConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Disconnected.
        /// </summary>
        internal static string GameServer_Log_ServerDisconnected {
            get {
                return ResourceManager.GetString("GameServer_Log_ServerDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Connected.
        /// </summary>
        internal static string ScoreServer_Log_ClientConnected {
            get {
                return ResourceManager.GetString("ScoreServer_Log_ClientConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Failed to Connect.
        /// </summary>
        internal static string ScoreServer_Log_ClientConnectFailed {
            get {
                return ResourceManager.GetString("ScoreServer_Log_ClientConnectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Disconnected.
        /// </summary>
        internal static string ScoreServer_Log_ClientDisconnected {
            get {
                return ResourceManager.GetString("ScoreServer_Log_ClientDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listening for Web Clients on Port 80.
        /// </summary>
        internal static string ScoreServer_Log_ServerConnected {
            get {
                return ResourceManager.GetString("ScoreServer_Log_ServerConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Disconnected.
        /// </summary>
        internal static string ScoreServer_Log_ServerDisconnected {
            get {
                return ResourceManager.GetString("ScoreServer_Log_ServerDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **** SERVER STOPPED. PRESS ANY KEY TO CLOSE ****.
        /// </summary>
        internal static string Server_Stopped_ExitMessage {
            get {
                return ResourceManager.GetString("Server_Stopped_ExitMessage", resourceCulture);
            }
        }
    }
}
